### ISSUE TITLE
Limit total number of changes per diff generation (osmosis compatibility)

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/osmdbt#10]
Osmosis has a somewhat complex logic to determine ranges of transaction xids. They are used as a baseline for one diff generation run. The calculation includes the current maximum xid as well as information from the previous state.txt file. Due to (perceived) SQL query length restrictions, those xid ranges have an upper bound, which effectively limits the total number of transactions to be extracted in one go.

Long story short, the effect of those limits is, that osmosis never creates diff files that exceed a certain number of underlying database transactions. I should note that xid is a global Postgresql transaction counter, that gets increased by any Rails changes, Database backups, probably vacuuming, etc. Depending on overall system load, that might translate into something like 5-15 minutes (that's my current best guess).

Why do I bring this up? In the (unlikely) event that replication processing stops and needs to be restarted, say 0.5 - 1 hour later, we want to have some control over the size of the generated diff files. It is better to more evenly distribute those changes over a period of time, rather than overwhelm data consumers with one single huge diff file.

IMHO the most difficult task is to find the number of changes for logical replication, which best matches the current osmosis logic. Possibly, a configurable parameter would be best? The idea is to pass this value to `pg_logical_slot_get_changes` as `upto_nchanges` parameter (instead of NULL).

Some pointers to the relevant osmosis code as reference:

- https://github.com/openstreetmap/osmosis/blob/master/osmosis-apidb/src/main/java/org/openstreetmap/osmosis/apidb/v0_6/impl/Replicator.java#L173-L184
- https://github.com/openstreetmap/osmosis/blob/master/osmosis-apidb/src/main/java/org/openstreetmap/osmosis/apidb/v0_6/impl/EntityDao.java#L424-L450
- https://github.com/openstreetmap/osmosis/blob/master/osmosis-apidb/src/main/java/org/openstreetmap/osmosis/apidb/v0_6/impl/EntityDao.java#L304-L354

The effect can be seen here: https://gist.github.com/mmd-osm/b7347d23c73aa869d19841d081710b8c
e.g. on 2014-04-18 after a 13 hours outage with several minutes of ~450000 OPL line items (excludes start/end of transaction marker)

And right now here: https://planet.openstreetmap.org/replication/minute/004/095/ , starting at file 147.

**Comment by mmd-osm** [comment]
Thanks for implementing this limit. I have a quick follow up question if you don’t mind: 

According to the Readme, create-diff can run in parallel to the other command line tools, and also pick up multiple log files. What would be the best way for a sysadmin to make sure that create diff considers the same upper limit, as get-log did before?

>  „osmdbt-create-diff can handle any number of log files, so if it is not run for a while it will recover by reading all log files it finds and creating one replication diff file with the (sorted) data from all of them.“

**Comment by joto** [comment]
Sorry, I overlooked that `create-diff` merges the data from several log files.

**Comment by joto** [comment]
This should now be fixed.

**Comment by mmd-osm** [comment]
I'm just testing your changes and noticed something odd with no limits set. I assume options.max_changes() == 0 is supposed to mean "unlimited". However, the value compare below would always be true, if there's at least one entry in the todo list. This condition should probably be only true in case `options.max_changes() > 0`, or you need to initialize max_changes with a really large value (max_int or something).

```C++
 if (objects_todo.size() > options.max_changes()) {
            vout << "  Reached limit of " << options.max_changes()
                 << " objects.\n";
            break;
```

[ 0:00]   Got 3 objects.
[ 0:00]   Reached limit of 0 objects.
[ 0:00] Populating changeset cache...
[ 0:00]   Got 2 changesets.

**Comment by joto** [comment]
@mmd-osm Thanks for finding this. Just fixed it.

**Comment by mmd-osm** [comment]
Thanks, I'm closing this for the time being...

**Comment by mmd-osm** [comment]
Is there anything we need to do for fake-log? As we've seen recently, even looking at a time period of 6 hours would quickly accumulate a few million entries. fake-log currently only comes with a start timestamp, but has otherwise no limits.

One thing I could imagine is to calculate an (exclusive upper bound) timestamp_to in addition to the timestamp_from, and check that the total number of changes across nodes, ways and relations is still below some upper limit (`--split-every-n-items`). This can be accomplished by the following index-only operation:

```
SELECT date_trunc('second', MAX(timestamp)), count(*) FROM (
  SELECT * FROM (
     SELECT timestamp FROM nodes  UNION ALL
     SELECT timestamp FROM ways   UNION ALL
     SELECT timestamp FROM relations 
    ) a 
  WHERE a.timestamp >= '2020-05-23T11:34:44Z'   -- current timestamp_from
  ORDER BY a.timestamp
  LIMIT 500000   -- limit
) b;
```

Then iterate by creating a log file, setting the timestamp_from to the previous timestamp_to, etc.
This approach would be most suitable to quickly process a large backlog. As an alternative to a dynamically determined range, a user might want to specify a fixed window size (like 60 seconds), to mimic the usual diff processing (`--split-every-n-minutes`).

**Comment by joto** [comment]
I think we probably want to mimic the usual `get-log` processing here, ie. create minutely diffs (with some upper bound on the size). We should also make sure we don't create any empty files.

This would give us diff files which are as "similar" as possible to the normal operation which hopefully means the chances of this breaking some data consumer is the lowest.

**Comment by joto** [comment]
`osmdbt-fake-log` now writes minutely log files (8ca509c).

**Comment by joto** [comment]
I believe we have addressed all issues here. Closing.
