### ISSUE TITLE
Unit tests for create-diff

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/osmdbt#19]
osmdb-create-diff has quite a bit of logic inside. However, the unit test seems to check for an existing node/way id+version only.
I think it would be a good to check a few additional things:

* Test create, modify and delete operations and check that they end up with the correct enclosing XML tag `<create>`, `<modify>`, `<delete>`
* Check that each object header field is correctly filled, including timestamp, uid, user, and changeset id
* Check that all tags are included
* Check ways include all way nodes, sequence of nodes is correct
* Check relations include all relation members, members have correct member type and role, sequence of members is correct
* Changeset cache works correctly

Apologies, if I missed something that is already covered in the existing tests.

**Comment by joto** [comment]
The tests can't test everything. We assume that the underlying osmium library does the right thing here. That being said: If you want to write more tests, go ahead.

**Comment by mmd-osm** [comment]
Right. libosmium is only one piece of the overall process: create-diff issues a number of SQL statements and needs to pass those values on to libosmium. This glue code isn't sufficiently covered by unit tests, i.e. most changes to the SQL statements or calls to libosmium will still pass the unit test, even though they would break the end-to-end processing.

**Comment by mmd-osm** [comment]
Would you be ok with an SQL script as input including a number of different cases, and corresponding osm.osc files as output, and diff both files? The _generator_ attribute in the header would be replaced with some generic text.

That's not exactly in the spirit of testing one thing at a time, otoh, I don't want to create a new shell script for each test case, and iterating over multiple test files in one shell script would be defeated by the necessary cleanup that comes for free with pg_virtualenv.

**Comment by joto** [comment]
@mmd-osm Having an integration test like this that makes sure the whole thing together works as expected sounds like a good way to go.

**Comment by joto** [comment]
There are more tests now for various objects added, changed, deleted with and without tags etc. I believe this is okay now.
