### ISSUE TITLE
Should get-log check for existing log files with same LSN?

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/osmdbt#21]
db.cpp, function catchup_to_lsn has a comment _"If the advance didn't work it probably means we already have advanced, so that's okay._".

To better understand if there might be an issue, if this step doesn't work as expected, I took the README example and commented out a call to osmdbt-catchup. As the "catch" in that function doesn't raise an error code, the net result should be the same.

Even if I execute this simulation script only once, and then switch back to the original file, I'm getting multiple log files with the same LSN but different timestamps. This translates into identical osc.gz files later on.

I was wondering, if it would be a reasonable thing for `osmdbt-get-log` to check for existing (un-)processed log files with the same LSN, and complain, warn or abort processing? 

The other question would be, if osmdbt-catchup can check if the catch up did actually happen. There seem to be some limits to that for versions below 10, according to the code in osmdbt-testdb?

```
#!/bin/sh

set -e

./osmdbt-catchup
./osmdbt-get-log
# optionally copy log file(s) to other hosts

# Simulate catchup_to_lsn did not work (-> no error code)
#./osmdbt-catchup
./osmdbt-create-diff
```

Multiple files in log directory with same LSN:

```
 915 Jul 16 16:16  osm-repl-2020-07-16T14:16:43Z-lsn-60-40994D28.log.done
 915 Jul 16 16:16  osm-repl-2020-07-16T14:16:47Z-lsn-60-40994D28.log.done
```

**Comment by joto** [comment]
I looked into this and now don't think there is any reason why this should fail in normal operation. So I have removed the try/catch block. If this ever fails, we'll see it and can then deal with it like with any other problem. If we find out later there is a specific case where this can fail and it doesn't matter, we have to figure out then how better to distinguish this failure from any other.
