### ISSUE TITLE
Fetching objects in create-diff (osmosis performance regression)

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/osmdbt#24]
I did a small performance regression test using the current `osmdbt` vs. `osmosis`, and noticed some slowdown overall. While `get-log` did pretty ok, there's quite some slowdown in `create-diff` to create osc.gz files.

As it stands, this is mainly caused by a large number of database selects: for each single node, way, and relation and their respective tags/way_nodes and members, a single SQL statement is sent to the database.

Depending on the object type, 500k new objects will result in about 1 to 1.5mio queries, that would need to fit into a minutely diff time frame.  Currently, I can't get osmdbt to fit in here, when running on the same host as the database (see test below).

Osmosis already uses bulk database access during replication. For this reason, I labeled this issue as _osmosis performance regression_.

Respective code from osmosis: https://github.com/openstreetmap/osmosis/blob/master/osmosis-apidb/src/main/java/org/openstreetmap/osmosis/apidb/v0_6/impl/EntityDao.java#L114-L142

CGImap as an example uses the following pattern for bulk fetches: https://github.com/zerebubuth/openstreetmap-cgimap/blob/master/src/backend/apidb/readonly_pgsql_selection.cpp#L136-L159 (ignore the LEFT JOIN on node_tags, that's not relevant here).

Ideally, bulk processing should come with a configurable parameter to control the number of objects to be fetched in one query.

## Test

Database version: PostgreSQL 9.5.22, local database, running on SSD. Results consistent across several test runs.

500k ways added, no way_nodes, no tags

|  Step | Runtime 
--- | ---:| 
| osmosis                    |  8s 
| |
| osmdbt-get-log --catchup |  12s 
| /osmdbt-create-diff |      101s 
|   - (includes parsing log file) | 2s

Osmosis: .`/osmosis --replicate-apidb authFile=dbauth.txt allowIncorrectSchemaVersion=true validateSchemaVersion=no --write-replication workingDirectory=data`

**Comment by joto** [comment]
I'll work on reducing the number of db queries.

**Comment by mmd-osm** [comment]
Closing as fix was provided in #28
