### ISSUE TITLE
fake-log, isolation level and concurrent txns

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/osmdbt#25]
pqxx::work transaction assumes an isolation level read_committed, which could result in both non-repeatable and phantom reads (see https://www.postgresql.org/docs/9.5/transaction-iso.html).

This may lead to inconsistent results in `fake-log` when several SQL statements for nodes, ways and relations are executed in a row, while users are still uploading changesets at the same time. As an example: the "way" query fetches new ways that reference nodes, which weren't committed yet at the time the "node" query was executed -> log file is missing some "node" entries later on.

It would be better to use isolation level _repeatable read_:

> _This level is different from Read Committed in that a query in a repeatable read transaction sees a snapshot as of the start of the first non-transaction-control statement in the transaction, not as of the start of the current statement within the transaction. Thus, successive SELECT commands within a single transaction see the same data, i.e., they do not see changes made by other transactions that committed after their own transaction started._

The other issue that fake-log needs to address are "in-flight" transactions, as mentioned by @zerebubuth in https://github.com/openstreetmap/operations/issues/154#issue-213602150: _This is the problem with timestamps - we have no way to ensure that all the changes before a particular timestamp are visible to the replicator's transaction._

![image](https://user-images.githubusercontent.com/5842757/88486982-df29a280-cf81-11ea-9aa7-e75efc6f258c.png)

Osmosis currently evaluates txid_current_snapshot to check for any in-flight transactions (you can still see them in today's state.txt files as "txnActiveList=..."), or in the example below as "3043".

It would probably be best to try a few times, until no more in-flight transactions are around, and then start the `fake-log` extraction process. 

```
SELECT txid_current_snapshot();
 txid_current_snapshot 
-----------------------
 3043:3045:3043
```

By the way, Osmosis source code states the following rule re. transaction timestamp in the state.txt file:

_A key rule in replication is that the timestamp we specify in our replication state is always equal to or later than all data timestamps. This allows consumers to know that when they pick a timestamp to start  replicating from that *all* data created after that timestamp will be included in subsequent replications._

(Screenshot taken from https://habr.com/en/company/postgrespro/blog/479512/)

**Comment by joto** [comment]
It doesn't really make sense to run fake-log on a database that is actively being changed. I would expect that you are using it in a situation where you have stopped updates, you run the fake-log, enable replication and only then you allow changes again. Otherwise you don't know have a clean place where to switch from fake-log to normal get-log processing.

**Comment by mmd-osm** [comment]
I was thinking more in terms how the process works today. Changeset upload and diff generation are fairly independent processes, i.e. when the diff generation breaks down, you can restart it later without affecting the changeset upload. I don't recall that we ever shut down changeset upload because of any subsequent issues with replication.

If the new process is designed to require some mandatory read-only period for cases where fake-log is needed, this needs at least to be documented somewhere for the sysops team. Maybe @tomhughes can chime in here, if he's happy with this approach.

**Comment by joto** [comment]
fake-log is just a "last ditch" tool. It would only be used if the replication mechanism breaks down or if we are moving databases or something like that. This never happened before, because there wasn't a replication mechanism that could fail. So any case where I can imagine this would be use is one where the database is down for some reason or another anyway.

I have added some docs to the fake-log man page.

**Comment by mmd-osm** [comment]
Thanks, I think https://github.com/openstreetmap/osmdbt/commit/e30e8cf713b48ced88dce22ce7b7fd8bf0f432da makes it sufficiently clear now how fake-log is supposed to be used in production. Due to explicit "read-only" mode, we don't need additional logic in the code. Let's hope that sysadmins read the documentation before using the tool :)
