### ISSUE TITLE
Order of tags in object

### ISSUE THREAD

**Issue by joto** [openstreetmap/osmdbt#29]
The current code of osmdbt-create-diff will write out tags of an OSM object ordered by the key. This makes sure that there is a defined order and that running the code twice will get you the same result.

I believe this is different from
* how Osmosis does it and
* how [planet-dump-ng](https://github.com/zerebubuth/planet-dump-ng) does it

We recently had the case where somebody complained to me that updating a planet file with changes and comparing the resulting objects to the next planet file dump showed differences between them because of differently ordered tags. Yes, we don't guarantee any kind of tag order in OSM files, but it would occasionally be useful, like in this case.

Should tags be ordered? Opinions?

@zerebubuth

**Comment by zerebubuth** [comment]
It might be surprising, but the tags _are_ ordered in `planet-dump-ng`! :exploding_head: :wink: 

However, they might not be ordered in a way that makes sense at first glance. The keys are serialised to a sequence of bytes by:

1. Encoding the string as UTF-8.
2. Taking the length of the UTF-8 bytes.
3. Prepending the length as a varint (i.e: 7-bits per byte LSB-first with the high order as continuation bit).

And keys are sorted string-wise on this sequence of bytes. What this means is that the order _is_ consistent, but perhaps not usefully so to anyone consuming the planet dump. The effect of this (given that tag keys tend to be ASCII and <128 bytes) is that you should mostly see shorter keys first, and keys of the same length should be sorted alphabetically. It'll be (very) different for keys which are not ASCII, though!

I'd be interested in making this more useful to consumers of the planet file, but it's a constraint of the current implementation of `planet-dump-ng` that it sorts records based on their _encoded_ values. So if we can work out an order that's both useful to planet consumers and is easily sortable as bytes, that would save a lot of effort (and CPU cycles). Would sorting on the UTF-8 encoded bytes be OK?

**Comment by joto** [comment]
Any kind of "real" sorting on unicode strings (which would include issues such as locales, languages, encoding variants etc.) is hopeless (and much too expensive) anyway. Even if we defined something like this, we'd never be sure everbody would implement it in the same way.

So the best we can do is come up with some ordering thats simple and cheap to do. And sorting on the UTF-8 encoded bytes would fit that bill. That should just be the same as `LC_COLLATE=C` and can easily be done in C++, in the database, and in any other programming language.

**Comment by zerebubuth** [comment]
I've just pushed the code for [v.1.2.0 of `planet-dump-ng`](https://github.com/zerebubuth/planet-dump-ng/releases/tag/v1.2.0) with the change to tag ordering. I'll make the change to Chef soon, too. Then next week's planet dump should include the new ordering.

**Comment by joto** [comment]
Okay, I have this in osmdbt. 0c258d6
