### ISSUE TITLE
state.txt

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/osmdbt#3]
I do realize that this repo is still in an early stage. Do you have plans to provide a state.txt file in the future, and if so to what extent would you be able to replicate today’s file contents?

**Comment by joto** [comment]
Yes, this should at some point create state files that are compatible to the current way things are handled. At the moment I am not sure yet, where exactly and how to handle this. It will either be part of `osmdbt-create-diff` or an extra process that takes the diff from `osmdbt-create-diff` and does all the state file handling.

**Comment by mmd-osm** [comment]
Apparently @zerebubuth already created some Ruby script to address the state.txt file issue: https://github.com/zerebubuth/openstreetmap-replication-ng

**Comment by zerebubuth** [comment]
Yes, although @joto and I discussed it, and a lot (most?) of the stuff the Ruby script is doing might be better merged into the C++ tools. I should update the script README to say it's obsolete/experimental.

As for the `state.txt`, hopefully the only fields people are relying on are the `sequenceNumber` and `timestamp`. (Do we need to bug-for-bug emulate the `\` escaped colons in the timestamp?) We can add fake `txn*` fields if absolutely necessary, but I'd rather not.

When we get this up & running for testing (on the dev server?), hopefully we can check that it doesn't break widely-used clients.

**Comment by mmd-osm** [comment]
I just responded to your second paragraph in the other issue (https://github.com/zerebubuth/openstreetmap-replication-ng/issues/1#issuecomment-590101550).

I'm currently not aware of any application using those `txn*` fields. The only relevant information you could derive from it are some inflight transactions as an indicator that more data for the current timestamp is still to come in a subsequent diff file. However, this isn't precise in any way, i.e. you can't rely on it anyway.

> When we get this up & running for testing (on the dev server?), hopefully we can check that it doesn't break widely-used clients.

Yes, that's something I'd definitely recommend. People were always looking for ways to get some diff files on the dev server, and that would be a pretty good opportunity to do so.

**Comment by joto** [comment]
The `state.txt` can be created now.

The `txn*` fields are not created. Unless somebody actually uses them or an important client fails if they are not there, we'll leave them out. Otherwise we have to fake them somehow. Also the comment in the first line `# DATE` is not created currently, we'll see if anybody needs it. Apart from that the `state.txt` should be compatible, including the escaping of the `:`. Closing here. Please open a new issue if there are problems during testing.
