### ISSUE TITLE
Documenting state.txt file format

### ISSUE THREAD

**Issue by joto** [openstreetmap/osmdbt#33]
I have documented the `state.txt` file format [here](https://github.com/openstreetmap/osmdbt/blob/master/man/osmdbt-state.txt.md).
Its a bit difficult, because it is a "legacy" format. Any comments on that welcome.

We should probably also document the file system structure of the diff/state files.

**Comment by mmd-osm** [comment]
A few comments:

#### Properties:

> sequenceNumber : The sequence number of this change file. Monotonically increasing from one file to the next. Diff files are expected to be read in the order of this sequence number. Do not rely on there not being holes in the sequence.

I don't recall that we allowed gaps in the sequence, and I'm pretty sure a lot of tools would break if we did so. Did you find any documentation on this topic somewhere else?

#### History section:

In case people are wondering why newer state.txt files lack some of the fields which were previously generated by osmosis, a bit of history might be helpful:

state.txt files generated by osmosis included additional fields txnMaxQueried, txnReadyList, txnMax, txnActiveList. Those were strictly osmosis-internal and are not supported by osmdbt.

#### See also:

Maybe add a link on how to process state.txt files in general:

* https://wiki.openstreetmap.org/wiki/Planet.osm/diffs  -> describes the exact sequence for fetching state.txt files from the server

By the way, looking at that wiki page, there are still some references to the old txn* fields generated by osmosis...

**Comment by joto** [comment]
Thanks @mmd-osm, I have added those changes to the man page.
