### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by joto** [openstreetmap/osmdbt#34]
The CI (using Github actions) of this repository is broken, because Guthub keeps changing the images it runs on. We need a better, stable CI. Ideas and help welcome.

**Comment by mmd-osm** [comment]
Can you try this one: https://github.com/actions/virtual-environments/issues/3397

They seem to have removed PostgreSQL in their Ubuntu image, and provide instructions to install it from the Postgres apt repo instead.

**Comment by joto** [comment]
@mmd-osm Fixing things based on their broken CI is not a sustainable way forward. We need a better solution than that.

**Comment by mmd-osm** [comment]
Ok, the next best thing I can think of is to use a Dockerfile and run tests inside a docker container. I’m already doing that for cgimap to have more control over the build environment, while still using GitHub actions.

**Comment by joto** [comment]
Fixed now.
