### ISSUE TITLE
Build for Ubuntu 22.04

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/osmdbt#37]
Can we get a launchpad build for jammy aka 22.04 please @mmd-osm?

**Comment by mmd-osm** [comment]
I uploaded commit c03a67558b80ae00cbd881b0b4b2a458bc3540d1 to https://launchpad.net/~mmd-osm/+archive/ubuntu/osmdbt-006 , build looks ok, publishing is still pending.

@joto : can you add a <code>v0.6</code> tag to this commit and make it available as released version here? https://github.com/openstreetmap/osmdbt/releases

**Comment by joto** [comment]
@mmd-osm Now available.

**Comment by mmd-osm** [comment]
Thanks. PPA is available here in the meantime: https://launchpad.net/~osmadmins/+archive/ubuntu/ppa

Nothing left to do, let's close this one.
