### ISSUE TITLE
osmdbt and first minute diff

### ISSUE THREAD

**Issue by lamisofteu** [openstreetmap/osmdbt#40]
When I try run sequence of commands first time, I see error:

 0:00] Started osmdbt-create-diff
[ 0:00]   osmdbt version 0.6
[ 0:00]   libosmium version 2.18.0
[ 0:00] Reading config from '/etc/osmdbt-config.yaml'
[ 0:00] Config:
[ 0:00]   Database:
[ 0:00]     Host: localhost
[ 0:00]     Port: 5432
[ 0:00]     Name: osm
[ 0:00]     User: openstreetmap
[ 0:00]     Password: (not shown)
[ 0:00]     Replication Slot: osm_repl
[ 0:00]   Directory for log files: /tmp/
[ 0:00]   Directory for change files: /planet/replication/minute/data/
[ 0:00]   Directory for tmp files: /tmp/
[ 0:00]   Directory for run files: /tmp/
[ 0:00] No log files on command line. Looking for log files in log directory...
[ 0:00] 1 log files to read.
[ 0:00] Connecting to database...
[ 0:00] Database version: PostgreSQL 14.11 (Ubuntu 14.11-0ubuntu0.22.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, 64-bit
[ 0:00] Reading log file '/tmp/osm-repl-2024-03-09T15:54:16Z-lsn-17-67B2B088.log'...
[ 0:00]   Got 6 nodes, 1 ways, 0 relations.
[ 0:00] Populating changeset cache...
[ 0:00]   Got 1 changesets.
[ 0:00] Opening output file '/tmp/new-change.osc.gz'...
[ 0:00] Opening output file '/tmp/new-change.osc.pbf'...
[ 0:00] Processing 6 nodes, 1 ways, 0 relations...
[ 0:00] Wrote and synced output file.
[ 0:00] Writing state file '/tmp/new-state.txt'...
Missing state file: '/planet/replication/minute/data/state.txt'

How I can create file 'state.txt' first time?

Can anybody help with this?

**Comment by joto** [comment]
Are you sure osmdbt is the right tool for whatever it is that you are trying to do? What are you trying to do?
