### ISSUE TITLE
Handling redactions

### ISSUE THREAD

**Issue by joto** [openstreetmap/osmdbt#5]
Is there anything special we need to do to handle redactions?

**Comment by mmd-osm** [comment]
Osmosis was checking the redaction_id field when accessing historic versions: https://github.com/openstreetmap/osmosis/blob/2219470cef1f73f5d1319c57149c84b398e767ce/osmosis-apidb/src/main/java/org/openstreetmap/osmosis/apidb/v0_6/impl/EntityDao.java#L450

**Comment by joto** [comment]
This is now handled like in Osmosis.
