### ISSUE TITLE
disable-replication should check for remaining entries to be processed

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/osmdbt#9]
osmdbt-disable-replication does not check for any remaining entries to be processed in the replication slot. This may be dangerous as it could lead to loss of data.

pg_logical_slot_peek_changes offers a way to check for existing entries without removing them. Maybe this could be used for an additional check here.

An additional --force may be useful, in case you know what you're doing.

**Comment by joto** [comment]
All the commands here are for people who know what they are doing. There is no reason to ever use `osmdbt-disable-replication` in normal operations. I don't see we need anything extra here.

**Comment by mmd-osm** [comment]
Right, it's one of those rarely executed tasks that operators will typically have limited experience with. As this is all very new for them, adding a few handrails wouldn't hurt, especially it if means you might lose data.

Looking at the man page, there's also no indication that the replication slot will be deleted, and all remaining entries deleted as well with no chance of recovery. 

> Disable replication on the database. The database will no longer write changes to the internal relication slot.
